### ISSUE TITLE
problem with git submodule add

### ISSUE THREAD

**Issue by EvenSol** [equinor/NeqSimLive-api-template#3]
When trying to add a templateAPI as a submodule in NeqSimLive repo, I get an error when the templateAPI is internal (ok when it is public).

I get the following error when using git submodule add on a repo that is internal.
Any thing we can do to make it work? @asmfstatoil , @soofstad 

```
git submodule add https://github.com/equinor/testNeqSimLiveTemplate.git
Cloning into '/workspaces/NeqSimLive/testNeqSimLiveTemplate'...
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/equinor/testNeqSimLiveTemplate.git/': The requested URL returned error: 403
fatal: clone of 'https://github.com/equinor/testNeqSimLiveTemplate.git' into submodule path '/workspaces/NeqSimLive/testNeqSimLiveTemplate' failed
```

**Comment by asmfstatoil** [comment]
Eg fekk til dette lokalt, mistenker dette er eit problem som oppstår i codespace. Har du autentisert brukaren din der for skrivetilgang til github?

Om det virkar for public, men ikkje internal, kan det vere det er single sign on for equinor organisasjonen på github som ikkje er gjort rett?
